### ISSUE TITLE
config file

### ISSUE THREAD

**Issue by starfish1107** [tystuyfzand/gotify-mqtt#1]
when adding the mqtt-linux-amd64.so  to the gotify plugins dir  I cant restart gotify - maybe due to missing config file. where do I have to create it?

**Comment by tystuyfzand** [comment]
Do you have a log from it? Gotify initializes a default config and should let it start - unless I messed up in the code somewhere... I'll check it out later and patch it, I think I know what's wrong.

**Comment by starfish1107** [comment]
`Jul 22 21:25:01 mybasel CRON[2905]: (root) CMD ([ -x /usr/sbin/dma ] && /usr/sbin/dma -q1)
Jul 22 21:25:02 mybasel systemd[1]: Stopping Gotify Push Notification Server...
Jul 22 21:25:02 mybasel systemd[1]: gotify.service: Main process exited, code=killed, status=15/TERM
Jul 22 21:25:02 mybasel systemd[1]: gotify.service: Succeeded.
Jul 22 21:25:02 mybasel systemd[1]: Stopped Gotify Push Notification Server.
Jul 22 21:25:02 mybasel systemd[1]: Started Gotify Push Notification Server.
Jul 22 21:25:02 mybasel gotify[2913]: Starting Gotify version 2.0.21@2021-01-06-15:38:32
Jul 22 21:25:02 mybasel gotify[2913]: fatal error: runtime: no plugin module data
Jul 22 21:25:02 mybasel gotify[2913]: goroutine 1 [running]:
Jul 22 21:25:02 mybasel gotify[2913]: runtime.throw(0x10c6fed, 0x1e)
Jul 22 21:25:02 mybasel gotify[2913]: #011/usr/local/go/src/runtime/panic.go:1116 +0x72 fp=0xc00021f4c8 sp=0xc00021f498 pc=0x736612
Jul 22 21:25:02 mybasel gotify[2913]: plugin.lastmoduleinit(0xc0003cbc80, 0x1001, 0x1001, 0xc000011bf8, 0x284d4e0)
Jul 22 21:25:02 mybasel gotify[2913]: #011/usr/local/go/src/runtime/plugin.go:20 +0xb30 fp=0xc00021f5e8 sp=0xc00021f4c8 pc=0x767510
Jul 22 21:25:02 mybasel gotify[2913]: plugin.open(0xc0003a94c0, 0x1d, 0x3, 0xc0003a94c0, 0x20)
Jul 22 21:25:02 mybasel gotify[2913]: #011/usr/local/go/src/plugin/plugin_dlopen.go:77 +0x51c fp=0xc00021f860 sp=0xc00021f5e8 pc=0xdd41dc
Jul 22 21:25:02 mybasel gotify[2913]: plugin.Open(...)
Jul 22 21:25:02 mybasel gotify[2913]: #011/usr/local/go/src/plugin/plugin.go:32
Jul 22 21:25:02 mybasel gotify[2913]: github.com/gotify/server/v2/plugin.(*Manager).loadPlugins(0xc0003b5080, 0xc000325a60, 0xc, 0x16242a0, 0xc000011be0)
Jul 22 21:25:02 mybasel gotify[2913]: #011/proj/plugin/manager.go:230 +0x1ee fp=0xc00021f950 sp=0xc00021f860 pc=0xdd82ee
Jul 22 21:25:02 mybasel gotify[2913]: github.com/gotify/server/v2/plugin.NewManager(0x16242a0, 0xc000011be0, 0xc000325a60, 0xc, 0xc0003b5040, 0x1602100, 0xc0003b5000, 0x70ded0, 0xc0003cfc70, 0x10)
Jul 22 21:25:02 mybasel gotify[2913]: #011/proj/plugin/manager.go:86 +0x190 fp=0xc00021faa0 sp=0xc00021f950 pc=0xdd7330
Jul 22 21:25:02 mybasel gotify[2913]: github.com/gotify/server/v2/router.Create(0xc000011be0, 0xc0003a4870, 0xc000115500, 0xe, 0xc000325a10)
Jul 22 21:25:02 mybasel gotify[2913]: #011/proj/router/router.go:44 +0x78b fp=0xc00021fec0 sp=0xc00021faa0 pc=0xe5328b
Jul 22 21:25:02 mybasel gotify[2913]: main.main()
Jul 22 21:25:02 mybasel gotify[2913]: #011/proj/app.go:51 +0x385 fp=0xc00021ff88 sp=0xc00021fec0 pc=0xe8a725
Jul 22 21:25:02 mybasel gotify[2913]: runtime.main()
Jul 22 21:25:02 mybasel gotify[2913]: #011/usr/local/go/src/runtime/proc.go:204 +0x209 fp=0xc00021ffe0 sp=0xc00021ff88 pc=0x739029
Jul 22 21:25:02 mybasel gotify[2913]: runtime.goexit()
Jul 22 21:25:02 mybasel gotify[2913]: #011/usr/local/go/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc00021ffe8 sp=0xc00021ffe0 pc=0x76c421
Jul 22 21:25:02 mybasel gotify[2913]: goroutine 7 [select]:
Jul 22 21:25:02 mybasel gotify[2913]: database/sql.(*DB).connectionOpener(0xc0003ae340, 0x16192e0, 0xc0003b47c0)
Jul 22 21:25:02 mybasel gotify[2913]: #011/usr/local/go/src/database/sql/sql.go:1126 +0xf5
Jul 22 21:25:02 mybasel gotify[2913]: created by database/sql.OpenDB
Jul 22 21:25:02 mybasel gotify[2913]: #011/usr/local/go/src/database/sql/sql.go:740 +0x12a
Jul 22 21:25:02 mybasel gotify[2913]: goroutine 8 [chan receive]:
Jul 22 21:25:02 mybasel gotify[2913]: github.com/gotify/server/v2/plugin.NewManager.func1(0xc0003b5080, 0x16242a0, 0xc000011be0, 0x1602100, 0xc0003b5000)
Jul 22 21:25:02 mybasel gotify[2913]: #011/proj/plugin/manager.go:69 +0xf2
Jul 22 21:25:02 mybasel gotify[2913]: created by github.com/gotify/server/v2/plugin.NewManager
Jul 22 21:25:02 mybasel gotify[2913]: #011/proj/plugin/manager.go:67 +0x165
Jul 22 21:25:02 mybasel systemd[1]: gotify.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jul 22 21:25:02 mybasel systemd[1]: gotify.service: Failed with result 'exit-code'.
`

**Comment by starfish1107** [comment]
....
Jul 22 21:25:02 mybasel gotify[2913]: Starting Gotify version 2.0.21@2021-01-06-15:38:32
Jul 22 21:25:02 mybasel gotify[2913]: fatal error: runtime: no plugin module data

**Comment by tystuyfzand** [comment]
You're on Gotify v2.0.21 while the plugin is built for 2.0.23 - update your Gotify version and you should be fine :)

Edit: 2.0.23, not .32

**Comment by starfish1107** [comment]
you were right -it works now  thanks - its like xmas *smile*

**Comment by tystuyfzand** [comment]
Nice! Once that first plugin was done it was super easy to write another, biggest learning curve was the building. Glad you got it working and found it useful!

**Comment by starfish1107** [comment]
ill do some tests and keep you informed.
