### ISSUE TITLE
priority levels

### ISSUE THREAD

**Issue by starfish1107** [tystuyfzand/gotify-mqtt#3]
hi Tyler, just an idea - it would be nice to have priorities handed over to gotify. This would need a convention about how to mention the priority on mqtt-side (maybe simply "priority=x")

**Comment by tystuyfzand** [comment]
This should already be possible actually, if you can use JSON!

The plugin uses the base plugin API's Message struct, which lets you deserialize any message into it you want if it's JSON, for example:

```json
{
  "title":"Testing123",
  "message":"Some message",
  "priority":123,
  "extras":{ "some":"value" }
}
```

Note that all but message are completely optional here. I could also maybe define a format to use (like message="MESSAGE" priority=PRIORITY) but I think JSON is versatile enough that it should be reasonable to use.

**Comment by starfish1107** [comment]
great - sending json in mqtt payload did the job. thanks again.
